//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOI.Webforms
{
    public partial class ManageOrders
    {
        protected global::System.Web.UI.WebControls.GridView gvOrders;
        protected global::System.Web.UI.WebControls.Panel pnlOrderItems;
        protected global::System.Web.UI.WebControls.Literal litOrderItemsTitle;
        protected global::System.Web.UI.WebControls.GridView gvOrderItems;
    }
}
