//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOI.Webforms
{
    public partial class ProductDetails
    {
        protected global::System.Web.UI.WebControls.Image imgProduct;
        protected global::System.Web.UI.WebControls.Literal litProductName;
        protected global::System.Web.UI.WebControls.Literal litCategory;
        protected global::System.Web.UI.WebControls.Literal litPrice;
        protected global::System.Web.UI.WebControls.Literal litAvailability;
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;
        protected global::System.Web.UI.WebControls.Button btnAddToCart;
        protected global::System.Web.UI.WebControls.Literal litAddedMessage;
    }
}
